#!/bin/bash

# Script to help set up environment variables for Cloudflare Workers
# This generates secure secrets and provides instructions for setting them

echo "=========================================="
echo "Family Blog - Environment Setup"
echo "=========================================="
echo ""

# Generate secrets
JWT_SECRET=$(openssl rand -base64 32)
ADMIN_API_KEY=$(openssl rand -base64 24)

echo "Generated secure secrets:"
echo ""
echo "JWT_SECRET=$JWT_SECRET"
echo "ADMIN_API_KEY=$ADMIN_API_KEY"
echo ""
echo "=========================================="
echo "NEXT STEPS:"
echo "=========================================="
echo ""
echo "1. Go to Cloudflare Dashboard:"
echo "   https://dash.cloudflare.com"
echo ""
echo "2. Navigate to:"
echo "   Workers & Pages → family-blog → Settings → Variables"
echo ""
echo "3. Click 'Add variable' and add these secrets:"
echo "   - Name: JWT_SECRET"
echo "     Value: $JWT_SECRET"
echo "     Type: Secret (encrypt)"
echo ""
echo "   - Name: ADMIN_API_KEY"
echo "     Value: $ADMIN_API_KEY"
echo "     Type: Secret (encrypt)"
echo ""
echo "4. Click 'Save and Deploy'"
echo ""
echo "=========================================="
echo "CREATE ADMIN USER:"
echo "=========================================="
echo ""
echo "After setting the environment variables, create an admin user:"
echo ""
echo "curl -X POST https://family-blog.frankrobertdenton.workers.dev/api/admin/users \\"
echo "  -H 'Content-Type: application/json' \\"
echo "  -H 'x-admin-key: $ADMIN_API_KEY' \\"
echo "  -d '{"
echo "    \"email\": \"admin@yourdomain.com\","
echo "    \"password\": \"your-secure-password\","
echo "    \"name\": \"Admin User\""
echo "  }'"
echo ""
echo "=========================================="
echo "IMPORTANT: Save these credentials securely!"
echo "=========================================="
echo ""
