#!/bin/bash

# Quick setup script for environment variables
echo "=========================================="
echo "Family Blog - Environment Variable Setup"
echo "=========================================="
echo ""
echo "Your application is deployed but needs environment variables set."
echo ""
echo "🔑 Required Environment Variables:"
echo ""
echo "1. JWT_SECRET"
echo "   Value: rSWZPa07nkARr6lzYUyB/oPmbRvLLsEgQnu3M3jbyXY="
echo ""
echo "2. ADMIN_API_KEY"
echo "   Value: fH0+709DsWRIFRydYQGSsz80KCCcq/gb"
echo ""
echo "=========================================="
echo "Setup Instructions:"
echo "=========================================="
echo ""
echo "1. Go to: https://dash.cloudflare.com"
echo "2. Navigate: Workers & Pages → family-blog → Settings → Variables"
echo "3. Click 'Add variable' for each:"
echo "   - Variable name: JWT_SECRET"
echo "     Value: rSWZPa07nkARr6lzYUyB/oPmbRvLLsEgQnu3M3jbyXY="
echo "     Type: Text (not encrypted)"
echo ""
echo "   - Variable name: ADMIN_API_KEY"
echo "     Value: fH0+709DsWRIFRydYQGSsz80KCCcq/gb"
echo "     Type: Text (not encrypted)"
echo ""
echo "4. Click 'Save and Deploy'"
echo ""
echo "=========================================="
echo "After Setting Variables:"
echo "=========================================="
echo ""
echo "Test your site:"
echo "1. Visit: https://family-blog.frankrobertdenton.workers.dev"
echo "2. Sign in with existing credentials"
echo "3. Try creating a post, uploading an image, and sending a chat message"
echo ""
echo "All features should now work!"
echo "=========================================="
